# coding: utf-8
# MSDK/MGui framework build Sconscript
# $LastChangedDate:  $
# $LastChangedBy: dbacc $


import os, sys, fnmatch
import pyutils
import thirdparty

Import('env')
env_local = env.Clone()

# include dirs
env_local.AppendUnique(CPPPATH = ['./Includes',
                                  '../MCore/Includes',
                                  '#Maratis/Common'] )

# get list of files 
files = Glob('./Sources/*.c*',source=True)
if sys.platform=='win32':
    files.append(Glob('./Sources/WIN32/*.c*',source=True))
if sys.platform=='darwin':
    files.append(Glob('./Sources/COCOA/*.m*',source=True))

# build library
mgui_lib  = env_local.StaticLibrary('MGui',files)
Return('mgui_lib')

