# coding: utf-8
Import('env')
env_local = env.Clone()

# include dirs
env_local.AppendUnique(CPPPATH = [''] )

# get list of files
files = Glob('./*.c*')

# build library
stlib_lib  = env_local.StaticLibrary('stlib',files)
