# coding: utf-8
# Maratis/Common framework build Sconscript
# $LastChangedDate: 2011-02-12 01:11:34 +0100 (sam., 12 févr. 2011) $
# $LastChangedBy: dbacchet $


import os, sys, fnmatch
import pyutils
import thirdparty

Import('env')
env_local = env.Clone()

# include dirs
env_local.AppendUnique(CPPPATH = ['#MSDK/MCore/Includes',
                                  '#MSDK/MEngine/Includes',
								  '#MSDK/MGui/Includes',
								  '#MSDK/MaratisCore',
								  '#Maratis/Common'] )
# add 3rdparty libraries parameters
thirdparty.bullet.addBulletToEnv(env_local)
thirdparty.tinyxml.addTinyXmlToEnv(env_local)
thirdparty.devil.addDevilToEnv(env_local)
thirdparty.libsndfile.addLibSndFileToEnv(env_local)
thirdparty.freetype.addFreetypeToEnv(env_local)
thirdparty.lua.addLuaToEnv(env_local)

# get list of files 
files = pyutils.getFilesRecursive(Dir('.').srcnode().abspath,'*.c*')

# build library
maratiscommon_lib  = env_local.StaticLibrary('MaratisCommon',files)
Return('maratiscommon_lib')

