# coding: utf-8
# Maratis framework build Sconscript
# $LastChangedDate:  $
# $LastChangedBy: dbacc $


import os, sys, fnmatch
import pyutils
import thirdparty

Import('env')
env_local = env.Clone()

# include dirs
env_local.AppendUnique(CPPPATH = ['../shlib1',
                                  '../shlib2',
                                  '../stlib'] )
# lib dirs
env_local.AppendUnique(LIBPATH = ['../shlib1',
                                  '../shlib2',
                                  '../stlib'] )
# needed libs
env_local.AppendUnique(LIBS = ['shlib1',
                               'shlib2',
                               'stlib'] )

# get list of files (recursive)
files = Glob('*.c*')

# build application
test_exe  = env_local.Program('test_libcall',files,PDB='test_libcall.pdb')

