# coding: utf-8
# MSDK build Sconscript
#
# $LastChangedDate: 2008-05-12 12:03:21 +0200 (Mon, 12 May 2008) $
# $LastChangedBy: dbacc $


import os,sys

Import('env')



# build MGui
SConscript( 'MGui/SConscript',
            exports='env' )

# build MCore
SConscript( 'MCore/SConscript',
            exports='env' )

# build MEngine
SConscript( 'MEngine/SConscript',
            exports='env' )
