# coding: utf-8
Import('env')
env_local = env.Clone()

# include dirs
env_local.AppendUnique(CPPPATH = [''] )

# get list of files
files = Glob('./*.c*')

# build library
shlib2_lib  = env_local.SharedLibrary('shlib2',files,RPATH='@rpath')
