# coding: utf-8
Import('env')
env_local = env.Clone()

# include dirs
env_local.AppendUnique(CPPPATH = [''] )

# get list of files
files = Glob('./*.c*')

#env_local.AppendUnique(RPATH = 'ciccio')
#env_local['SHLINKCOM'] = env_local['SHLINKCOM'] + ' -install_name $RPATH'
# envdmp = env_local.Dump()
# print type(envdmp)
# outfile = open('myenv.txt','w')
# outfile.write(envdmp)
# outfile.close()
# build library
shlib1_lib  = env_local.SharedLibrary('shlib1',files)
